In [1]:
#pip install numpy as np

In [2]:
import numpy as np

In [3]:
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])
ket_plus = np.array([1, 1]) / np.sqrt(2)
ket_minus = np.array([1, -1]) / np.sqrt(2)
ket_plus_i = np.array([1, 1j]) / np.sqrt(2)
ket_minus_i = np.array([1, -1j]) / np.sqrt(2)


In [4]:
print("|0> = ", ket_0)
print("|1> = ", ket_1)
print("|+> = ", ket_plus)
print("|-> = ", ket_minus)
print("|+i> = ", ket_plus_i)
print("|->i> = ", ket_minus_i)

|0> =  [1 0]
|1> =  [0 1]
|+> =  [0.70710678 0.70710678]
|-> =  [ 0.70710678 -0.70710678]
|+i> =  [0.70710678+0.j         0.        +0.70710678j]
|->i> =  [ 0.70710678+0.j         -0.        -0.70710678j]


In [5]:
alpha = np.random.random()+np.random.random()*1j
beta = np.sqrt(1-alpha*np.conj(alpha))
phi = alpha*ket_0 + beta*ket_1

In [6]:
print(alpha)
print(beta)
print(phi)

(0.16169474408276352+0.34746773303669676j)
(0.9236454862307012+0j)
[0.16169474+0.34746773j 0.92364549+0.j        ]


In [7]:
print(np.dot(ket_0, ket_0))
print(np.dot(ket_1, ket_1))
print(np.dot(ket_plus, ket_plus))
print(np.dot(ket_minus, ket_minus))
print(np.dot(ket_plus_i, ket_plus_i))
print(np.dot(ket_minus_i, ket_minus_i))

1
1
0.9999999999999998
0.9999999999999998
0j
0j


In [8]:
print(np.dot(ket_0, ket_1))
print(np.dot(ket_plus, ket_minus))
print(np.dot(ket_plus_i, ket_minus_i))

0
0.0
(0.9999999999999998+0j)


In [9]:
p_0 = np.dot(ket_0, phi)
p_1 = np.dot(ket_1, phi)

In [10]:
print(p_0*np.conj(p_0))
print(p_1*np.conj(p_1))
print(p_0*np.conj(p_0)+p_1*np.conj(p_1))

(0.14687901576565157+0j)
(0.8531209842343485+0j)
(1+0j)


In [11]:
p_0 = np.dot(ket_plus, phi)
p_1 = np.dot(ket_minus, phi)

In [12]:
print(p_0*np.conj(p_0))
print(p_1*np.conj(p_1))
print(p_0*np.conj(p_0)+p_1*np.conj(p_1))

(0.6493486205192728+0j)
(0.35065137948072694+0j)
(0.9999999999999998+0j)


In [13]:
p_0 = np.dot(ket_plus_i, phi)
p_1 = np.dot(ket_minus_i, phi)

In [14]:
print(p_0*np.conj(p_0))
print(p_1*np.conj(p_1))
print(p_0*np.conj(p_0)+p_1*np.conj(p_1))

(0.8209370032301591+0j)
(0.17906299676984067+0j)
(0.9999999999999998+0j)


In [15]:
x_op = np.array([[0, 1], [1, 0]])
y_op = np.array([[0, -1j], [1j, 0]])
z_op = np.array([[1, 0], [0, -1]])
hadamard = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
cx_op = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])

In [16]:
conjugate_x_op = np.conj(x_op).T
conjugate_y_op = np.conj(y_op).T
conjugate_z_op = np.conj(z_op).T
conjugate_hadamard = np.conj(hadamard).T
conjugate_cx_op = np.conj(cx_op).T

In [17]:
print(np.all(x_op ==conjugate_x_op))
print(np.all(y_op == conjugate_y_op))
print(np.all(z_op == conjugate_z_op))
print(np.all(hadamard== conjugate_hadamard))
print(np.all(cx_op == conjugate_cx_op))

True
True
True
True
True


In [18]:
print(np.dot(x_op, ket_0))
print(np.dot(y_op, ket_0))
print(np.dot(z_op, ket_0))
print(np.dot(x_op, ket_1))
print(np.dot(y_op, ket_1))
print(np.dot(z_op, ket_1))
print(np.dot(x_op, ket_plus))
print(np.dot(y_op, ket_plus))
print(np.dot(z_op, ket_plus))
print(np.dot(x_op, ket_minus))
print(np.dot(y_op, ket_minus))
print(np.dot(z_op, ket_minus))
print(np.dot(x_op, ket_plus_i))
print(np.dot(y_op, ket_plus_i))
print(np.dot(z_op, ket_plus_i))
print(np.dot(x_op, ket_minus_i))
print(np.dot(y_op, ket_minus_i))
print(np.dot(z_op, ket_minus_i))

[0 1]
[0.+0.j 0.+1.j]
[1 0]
[1 0]
[0.-1.j 0.+0.j]
[ 0 -1]
[0.70710678 0.70710678]
[0.-0.70710678j 0.+0.70710678j]
[ 0.70710678 -0.70710678]
[-0.70710678  0.70710678]
[0.+0.70710678j 0.+0.70710678j]
[0.70710678 0.70710678]
[0.        +0.70710678j 0.70710678+0.j        ]
[0.70710678+0.j         0.        +0.70710678j]
[0.70710678+0.j         0.        -0.70710678j]
[0.        -0.70710678j 0.70710678+0.j        ]
[-0.70710678+0.j          0.        +0.70710678j]
[0.70710678+0.j         0.        +0.70710678j]


In [28]:
import numpy as np
from scipy.linalg import expm

def matrix_exp_taylor(M, terms=10):

    n = M.shape[0]
    result = np.eye(n) 
    M_power = np.eye(n)  
    factorial = 1
    
    for i in range(1, terms):
        factorial *= i
        M_power = np.dot(M_power, M)  
        result += M_power / factorial
    
    return result


M = np.array([[1, 2], [3, 4]])
result = matrix_exp_taylor(M, terms=20)
print("Matrix exponential using Taylor expansion:")
print(result)

scipy_result = expm(M)
print("\nMatrix exponential using scipy.linalg.expm:")
print(scipy_result)

print("\nDifference between Taylor and scipy results:")
print(np.abs(result - scipy_result))

Matrix exponential using Taylor expansion:
[[ 51.96890355  74.73648784]
 [112.10473176 164.07363531]]

Matrix exponential using scipy.linalg.expm:
[[ 51.9689562   74.73656457]
 [112.10484685 164.07380305]]

Difference between Taylor and scipy results:
[[5.26476479e-05 7.67301092e-05]
 [1.15095164e-04 1.67742812e-04]]


In [43]:
def anti_hermitian_matrix_exp_taylor(M, terms=10):

    n = M.shape[0]
    result = np.eye(n, dtype=complex) 
    M_power = np.eye(n, dtype=complex)  
    factorial = 1
    
    for i in range(1, terms):
        factorial *= i
        M_power = np.dot(M_power, 1j*M) 
        result += M_power / factorial
    
    return result

M = np.array([[1, 2], [3, 4]])
expiG  = anti_hermitian_matrix_exp_taylor(M, 20)
product = np.dot(expiG, np.conj(expiG.T).T)
print(np.dot(expiG, np.conj(expiG.T).T))


[[ 9.99969644e-01+4.12864187e-16j -4.42412231e-05+8.88178420e-16j]
 [-6.63618346e-05-7.21644966e-16j  9.99903282e-01-4.12864187e-16j]]
False


In [44]:
def u_op(theta, direction):
    operators = np.stack([x_op, y_op, z_op])
    dot_result = np.tensordot(direction, operators, axes=(0,0))
    u_op = expm(1j * theta/2 * dot_result)
    return u_op

print(u_op)

<function u_op at 0x0000020BF6CF18A0>


In [45]:
print(np.dot(u_op(np.pi, [1,0,0]), ket_0))
print(np.dot(u_op(np.pi, [0,1,0]), ket_0))
print(np.dot(u_op(np.pi, [0,0,1]), ket_0))
print(np.dot(u_op(np.pi, [1,0,0]), ket_1))
print(np.dot(u_op(np.pi, [0,1,0]), ket_1))
print(np.dot(u_op(np.pi, [0,0,1]), ket_1))

[6.123234e-17+0.j 0.000000e+00+1.j]
[ 6.123234e-17+0.j -1.000000e+00+0.j]
[6.123234e-17+1.j 0.000000e+00+0.j]
[0.000000e+00+1.j 6.123234e-17+0.j]
[1.000000e+00+0.j 6.123234e-17+0.j]
[0.000000e+00+0.j 6.123234e-17-1.j]


In [25]:
s_op = np.array([[1, 0],[0, 1j]])
t_op = np.array([[1, 0], [0, np.exp(1j*np.pi/4)]])

In [26]:
print(np.kron(ket_0, ket_0))

[1 0 0 0]


In [27]:
print(np.dot(hadamard, ket_0))
print(np.dot(hadamard, ket_1))
print(np.dot(cx_op, np.kron(ket_0, ket_0)))
print(np.dot(cx_op, np.kron(ket_plus, ket_0)))

[0.70710678 0.70710678]
[ 0.70710678 -0.70710678]
[1 0 0 0]
[0.70710678 0.         0.         0.70710678]
