In [1]:
import numpy as np

In [2]:
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])
ket_plus = np.array([1, 1]) / np.sqrt(2)
ket_minus = np.array([1, -1]) / np.sqrt(2)
ket_plus_i = np.array([1, 1j]) / np.sqrt(2)
ket_minus_i = np.array([1, -1j]) / np.sqrt(2)

alpha = np.random.random()
beta = np.sqrt(1-alpha**2)
ket_phi = alpha*ket_0 + beta*ket_1

In [3]:
i_op = np.eye(2)
rho_x_op = np.array([[0, 1], [1, 0]])
rho_y_op = np.array([[0, -1j], [1j, 0]])
rho_z_op = np.array([[1, 0], [0, -1]])

In [4]:
print(np.all(rho_x_op == rho_x_op.T))
print(np.all(rho_y_op == rho_y_op.T))
print(np.all(rho_z_op == rho_z_op.T))

True
False
True


In [5]:
print(np.all(np.dot(rho_x_op, rho_x_op) == i_op))
print(np.all(np.dot(rho_y_op, rho_y_op) == i_op))
print(np.all(np.dot(rho_z_op, rho_z_op) == i_op))

True
True
True


In [6]:
print(np.all(np.dot(i_op, ket_phi) == ket_phi))


True


In [7]:
print(np.dot(rho_x_op, ket_plus))
print(np.dot(rho_x_op, ket_minus))

print(np.dot(rho_y_op, ket_plus_i))
print(np.dot(rho_y_op, ket_minus_i))

print(np.dot(rho_z_op, ket_0))
print(np.dot(rho_z_op, ket_1))

[0.70710678 0.70710678]
[-0.70710678  0.70710678]
[0.70710678+0.j         0.        +0.70710678j]
[-0.70710678+0.j          0.        +0.70710678j]
[1 0]
[ 0 -1]


In [8]:
c0, c_x, c_y, c_z = 1,1,1,1
rho_op = c0*i_op + c_x*rho_x_op + c_y*rho_y_op + c_z*rho_z_op


In [9]:
print(np.trace(rho_x_op))
print(np.trace(rho_y_op))
print(np.trace(rho_z_op))

print(np.trace(np.dot(rho_x_op, rho_x_op)))
print(np.trace(np.dot(rho_x_op, rho_y_op)))
print(np.trace(np.dot(rho_x_op, rho_z_op)))

print(np.trace(np.dot(rho_y_op, rho_x_op)))
print(np.trace(np.dot(rho_y_op, rho_y_op)))
print(np.trace(np.dot(rho_y_op, rho_z_op)))

print(np.trace(np.dot(rho_z_op, rho_x_op)))
print(np.trace(np.dot(rho_z_op, rho_y_op)))
print(np.trace(np.dot(rho_z_op, rho_z_op)))


print(np.trace(np.dot(rho_x_op, rho_y_op)) == np.trace(np.dot(rho_y_op, rho_x_op)))

print(np.trace(np.dot(rho_op, i_op)))
print(np.trace(np.dot(rho_op, rho_x_op)))
print(np.trace(np.dot(rho_op, rho_y_op)))
print(np.trace(np.dot(rho_op, rho_z_op)))

0
0j
0
2
0j
0
0j
(2+0j)
0j
0
0j
2
True
(2+0j)
(2+0j)
(2+0j)
(2+0j)


In [10]:
density_matrix = np.dot(np.conj(rho_op).T, rho_op)

In [11]:
print(np.all(density_matrix == np.conj(density_matrix).T))

True


In [13]:
print(np.outer(ket_0, ket_0))
print(np.outer(ket_1, ket_1))

print(1/2*(i_op + rho_z_op))
print(1/2*(i_op - rho_z_op))

print(np.all(   np.outer(ket_0, ket_0) == 1/2*(i_op + rho_z_op)))
print(np.all(np.outer(ket_1, ket_1) == 1/2*(i_op - rho_z_op)))


[[1 0]
 [0 0]]
[[0 0]
 [0 1]]
[[1. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 1.]]
True
True
