In [1]:
#pip install numpy as np

In [2]:
import numpy as np

In [3]:
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])
ket_plus = np.array([1, 1]) / np.sqrt(2)
ket_minus = np.array([1, -1]) / np.sqrt(2)
ket_plus_i = np.array([1, 1j]) / np.sqrt(2)
ket_minus_i = np.array([1, -1j]) / np.sqrt(2)


In [4]:
print("|0> = ", ket_0)
print("|1> = ", ket_1)
print("|+> = ", ket_plus)
print("|-> = ", ket_minus)
print("|+i> = ", ket_plus_i)
print("|->i> = ", ket_minus_i)

|0> =  [1 0]
|1> =  [0 1]
|+> =  [0.70710678 0.70710678]
|-> =  [ 0.70710678 -0.70710678]
|+i> =  [0.70710678+0.j         0.        +0.70710678j]
|->i> =  [ 0.70710678+0.j         -0.        -0.70710678j]


In [5]:
alpha = np.random.random()+np.random.random()*1j
beta = np.sqrt(1-alpha*np.conj(alpha))
phi = alpha*ket_0 + beta*ket_1

In [6]:
print(alpha)
print(beta)
print(phi)

(0.5220655465661846+0.5247864613641194j)
(0.6723442087632469+0j)
[0.52206555+0.52478646j 0.67234421+0.j        ]


In [7]:
print(np.dot(ket_0, ket_0))
print(np.dot(ket_1, ket_1))
print(np.dot(ket_plus, ket_plus))
print(np.dot(ket_minus, ket_minus))
print(np.dot(ket_plus_i, ket_plus_i))
print(np.dot(ket_minus_i, ket_minus_i))

1
1
0.9999999999999998
0.9999999999999998
0j
0j


In [8]:
print(np.dot(ket_0, ket_1))
print(np.dot(ket_plus, ket_minus))
print(np.dot(ket_plus_i, ket_minus_i))

0
0.0
(0.9999999999999998+0j)


In [9]:
p_0 = np.dot(ket_0, phi)
p_1 = np.dot(ket_1, phi)

In [10]:
print(p_0*np.conj(p_0))
print(p_1*np.conj(p_1))
print(p_0*np.conj(p_0)+p_1*np.conj(p_1))

(0.5479532649425235+0j)
(0.45204673505747645+0j)
(1+0j)


In [11]:
p_0 = np.dot(ket_plus, phi)
p_1 = np.dot(ket_minus, phi)

In [12]:
print(p_0*np.conj(p_0))
print(p_1*np.conj(p_1))
print(p_0*np.conj(p_0)+p_1*np.conj(p_1))

(0.8510077468285934+0j)
(0.14899225317140657+0j)
(1+0j)


In [13]:
p_0 = np.dot(ket_plus_i, phi)
p_1 = np.dot(ket_minus_i, phi)

In [14]:
print(p_0*np.conj(p_0))
print(p_1*np.conj(p_1))
print(p_0*np.conj(p_0)+p_1*np.conj(p_1))

(0.8528371381355229+0j)
(0.14716286186447686+0j)
(0.9999999999999998+0j)


In [15]:
x_op = np.array([[0, 1], [1, 0]])
y_op = np.array([[0, -1j], [1j, 0]])
z_op = np.array([[1, 0], [0, -1]])
hadamard = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
cx_op = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])

In [16]:
conjugate_x_op = np.conj(x_op).T
conjugate_y_op = np.conj(y_op).T
conjugate_z_op = np.conj(z_op).T
conjugate_hadamard = np.conj(hadamard).T
conjugate_cx_op = np.conj(cx_op).T

In [17]:
print(np.all(x_op ==conjugate_x_op))
print(np.all(y_op == conjugate_y_op))
print(np.all(z_op == conjugate_z_op))
print(np.all(hadamard== conjugate_hadamard))
print(np.all(cx_op == conjugate_cx_op))

True
True
True
True
True


In [18]:
print(np.dot(x_op, ket_0))
print(np.dot(y_op, ket_0))
print(np.dot(z_op, ket_0))
print(np.dot(x_op, ket_1))
print(np.dot(y_op, ket_1))
print(np.dot(z_op, ket_1))
print(np.dot(x_op, ket_plus))
print(np.dot(y_op, ket_plus))
print(np.dot(z_op, ket_plus))
print(np.dot(x_op, ket_minus))
print(np.dot(y_op, ket_minus))
print(np.dot(z_op, ket_minus))
print(np.dot(x_op, ket_plus_i))
print(np.dot(y_op, ket_plus_i))
print(np.dot(z_op, ket_plus_i))
print(np.dot(x_op, ket_minus_i))
print(np.dot(y_op, ket_minus_i))
print(np.dot(z_op, ket_minus_i))

[0 1]
[0.+0.j 0.+1.j]
[1 0]
[1 0]
[0.-1.j 0.+0.j]
[ 0 -1]
[0.70710678 0.70710678]
[0.-0.70710678j 0.+0.70710678j]
[ 0.70710678 -0.70710678]
[-0.70710678  0.70710678]
[0.+0.70710678j 0.+0.70710678j]
[0.70710678 0.70710678]
[0.        +0.70710678j 0.70710678+0.j        ]
[0.70710678+0.j         0.        +0.70710678j]
[0.70710678+0.j         0.        -0.70710678j]
[0.        -0.70710678j 0.70710678+0.j        ]
[-0.70710678+0.j          0.        +0.70710678j]
[0.70710678+0.j         0.        +0.70710678j]


In [19]:
def u_op(thetha, direction):
    operators = np.stack([x_op, y_op, z_op])
    dot_result = np.tensordot(direction, operators, axes=(0,0))
    u_op = np.exp(1j * thetha/2 * dot_result)
    return u_op

print(u_op)


<function u_op at 0x000001AA635E59E0>


In [20]:
print(np.dot(u_op(np.pi, [1,0,0]), ket_0))
print(np.dot(u_op(np.pi, [0,1,0]), ket_0))
print(np.dot(u_op(np.pi, [0,0,1]), ket_0))
print(np.dot(u_op(np.pi, [1,0,0]), ket_1))
print(np.dot(u_op(np.pi, [0,1,0]), ket_1))
print(np.dot(u_op(np.pi, [0,0,1]), ket_1))

[1.000000e+00+0.j 6.123234e-17+1.j]
[1.        +0.j 0.20787958+0.j]
[6.123234e-17+1.j 1.000000e+00+0.j]
[6.123234e-17+1.j 1.000000e+00+0.j]
[4.81047738+0.j 1.        +0.j]
[1.000000e+00+0.j 6.123234e-17-1.j]


In [21]:
s_op = np.array([[1, 0],[0, 1j]])
t_op = np.array([[1, 0], [0, np.exp(1j*np.pi/4)]])

In [22]:
print(np.kron(ket_0, ket_0))

[1 0 0 0]


In [23]:
print(np.dot(hadamard, ket_0))
print(np.dot(hadamard, ket_1))
print(np.dot(cx_op, np.kron(ket_0, ket_0)))
print(np.dot(cx_op, np.kron(ket_plus, ket_0)))

[0.70710678 0.70710678]
[ 0.70710678 -0.70710678]
[1 0 0 0]
[0.70710678 0.         0.         0.70710678]
